language: go

go:
    - 1.11.x
    - 1.12.x
    - 1.13.x
    - 1.14.x
    - 1.x
    - master

install:
    - go get -u golang.org/x/tools/cmd/goimports
    - go get -u golang.org/x/lint/golint

script:
    - go vet ./...
    - diff <(goimports -d .) <(printf "")
    - diff <(golint ./...) <(printf "")
    - go test ./... -cover
