name: CI

on:
  push:
  pull_request:
    branches: [ master ]
    
jobs:
  
  test:
    strategy:
      matrix:
        go:
        - 1.18.x
        - 1.19.x
        - 1.20.x
        - 1.x
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        make dev

    - name: Test
      run: |
        diff <(goimports -d .) <(printf "")
        go vet ./...
        go test ./... -cover
